# -*- coding: utf-8 -*-
"""EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uxnK1DgbJaygmPshuojsu_68Fheinmfd
"""

import pandas as pd
import numpy as np
import  matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

df = pd.read_csv('Cardiotocographic.csv')
df.head()

df.info()

df.isnull().sum()

df.info()

sns.histplot(df['LB'],kde = True) # histplot to observe the distribution of 'LB' column
plt.title('LB distribution')
plt.show()

sns.boxplot(x = df['LB'])
plt.title('LB Boxplot')
plt.show() # boxplot to observe outliers

mean=df['LB'].mean() # mean of "LB" column
mean

df['LB'] = df['LB'].fillna(mean) # filling na values with mean as it is bell curved and having less outlier
df['LB']

df['LB'].isnull().sum() # It is  now clear that there are no null values in "LB" column

df.info()

sns.histplot(df['AC'],kde = True)
plt.title('AC distribution')
plt.show()

sns.boxplot(x = df['AC'] )
plt.title('AC boxplot')
plt.show()

df['AC'] = df['AC'].fillna(df['AC'].median)

df['AC'].isnull().sum()

sns.histplot(df['DS'],kde = True)
plt.title('DS distribution')
plt.show()

df['DS'].skew() #DS distribution is skewed but here we do not know whether it is left or right skewed
                     #so we use .skew() to know skewness, if skewness > 0 right skewed
                     #skewness < 0 then it is left skewed '''

df['DS']=df['DS'].fillna(df['DS'].median) # using median as it is skewed
df['DS'].isnull().sum() # null values are filled



sns.histplot(df['DL'],kde = True)
plt.title('DL distribution')
plt.show()

sns.boxplot(x=df['DL'])
plt.title('DL boxplot')
plt.show()

df['DL']=df['DL'].fillna(df['DL'].median)
df['DL'].isnull().sum() # Checking whether null values are filled

sns.histplot(df['DP'],kde = True)
plt.title('DP distribution')
plt.show()

df['DP'].skew() # DP distribution  is right skewed

df['DP']=df['DP'].fillna(df['DP'].median)
df['DP'].isnull().sum() # Checking whether null values are filled

sns.histplot(df['MLTV'],kde=True)
plt.title('MLTV distribution')
plt.show()

sns.boxplot(x=df['MLTV'])
plt.title('MLTV boxplot')
plt.show()

df['MLTV']=df['MLTV'].fillna(df['MLTV'].median)
df['MLTV'].isnull().sum()

sns.histplot(df['Width'],kde = True)
plt.title('width distribution')
plt.show()

df['Width'].skew() # Right skewed

df['Width']=df['Width'].fillna(df['Width'].median)
df['Width'].isnull().sum()

sns.histplot(df['Tendency'],kde = True)
plt.title('Tendency distribution')
plt.show()

df['Tendency'].skew() # Left skewed

df['Tendency']=df['Tendency'].fillna(df['Tendency'].median)
df['Tendency'].isnull().sum()

sns.histplot(df['NSP'],kde = True)
plt.title('NSP distribution')
plt.show()

df['NSP'].skew() # Right skewed

df['NSP'] = df['NSP'].fillna(df['NSP'].median)
df['NSP'].isnull().sum()

df.select_dtypes(include = 'object').columns # Looks like there are col with object dtype

cols_to_numeric = ['AC', 'DS', 'DP', 'MLTV', 'Width','Tendency','NSP']
for col in cols_to_numeric:
  df[col] = pd.to_numeric(df[col],errors = 'coerce')
# converting object dtypes into numerical as all values in cols are numerical

df.select_dtypes(include = 'object').columns  # conversion of object dtype to numerical is achieved

df.select_dtypes(include='number').columns
numeric_cols = ['LB', 'AC', 'FM', 'UC', 'DL', 'DS', 'DP', 'ASTV', 'MSTV', 'ALTV',
       'MLTV', 'Width', 'Tendency', 'NSP']

# Detecting outliers using boxplot
plt.figure(figsize =(15,10))
for i,col in enumerate(numeric_cols):
  plt.subplot(5,4,i + 1)
  sns.boxplot(y = df[col])
  plt.title(col)
  plt.show()

# Dectecting outlier using IQR method
for col in numeric_cols:
  Q1 = df[col].quantile(0.25)
  Q3 = df[col].quantile(0.75)
  IQR = Q3 - Q1
  lower_whisker = Q1 - 1.5 * IQR
  upper_whisker = Q3 + 1.5 * IQR
  outliers = df[(df[col] < lower_whisker)| (df[col] > upper_whisker )]
  print(f"{col}: {len(outliers)} outliers")

# Treating outliers with winsorization capping method
''' In this method  all the values below 5th percentile
and above 95th percentile are assumed to be outliers'''
from scipy.stats.mstats import winsorize
winsorized_df=df.copy()
for col in numeric_cols:
  winsorized_df[col] = winsorize(df[col],(0.05,0.05))
  print(winsorized_df)                                                # (0.05,0.05) are the percentile limits

import seaborn as sns
import matplotlib.pyplot as plt

for col in numeric_cols:
    plt.figure(figsize=(10,4))
    sns.kdeplot(df[col], label='Before', shade=True)
    sns.kdeplot(winsorized_df[col], label='After', shade=True)
    plt.title(f'{col} - Before vs After Winsorization')
    plt.legend()
    plt.show()

# checking the outliers with describe() before and after winsorization
for col in numeric_cols:
  print(f"before:,{df[col].describe()}")
  print(f"After:{winsorized_df[col].describe()}")

# Summarising stats of each column

for col in numeric_cols:
  print(f"{col}")
  print(f"mean:{winsorized_df[col].mean():.2f}")
  print(f"median: {winsorized_df[col].median():.2f}")
  print(f"std: {winsorized_df[col].std():.2f}")
  print(f"minimum_value:{winsorized_df[col].min():.2f}")
  print(f"maximum_value: {winsorized_df[col].max():.2f}")
  Q1 = winsorized_df[col].quantile(0.25)
  Q3 = winsorized_df[col].quantile(0.75)
  IQR = Q3 -Q1
  print(f"Q1:{Q1}")
  print(f"Q3:{Q3}")
  print(f"IQR:{IQR}")

# Summary and key findings
'''The dataset is about tracking fetus heart rate,stable heart rate means healthy fetus
cardiotocography in medical field is a technique that is used to monitor heart rate of the
fetus during pregnancy.Here the first thing to observe is fetal heart rate variability it is
about how the heart rate speed varies from beat to beat.good heart rate variability means
healthy baby.Another risk is abnormal fetal movements in medical term pathological cases
indicate a disease and for these cases fetal movements and abnormal heart rate variability is
high.Also in pathological cases deceleration leads to less oxygen supply to baby.Deceleration
is the term refers to droping of heart beat of baby and coming back to normal.here there are
three cases normal,suspect,pathological.A normal case requires less monitoring and checking
whereas a suspect case should be monitored daily.A pathological case must be given a higher
priority as baby with pathological case is at higher risk and must be monitored daily.'''

df[numeric_cols].hist(bins=20, figsize=(20, 15), color='skyblue', edgecolor='black')
plt.suptitle("Histograms of All Numerical Columns", fontsize=16)
plt.tight_layout()
plt.show()

sns.heatmap(df[numeric_cols].corr(),
            annot = True,
            cmap = 'coolwarm',
             center = 0,
              square = True,
              fmt = '.1f' )
plt.show()

sns.pairplot(df[['LB', 'AC', 'FM', 'UC', 'DL', 'DS', 'DP']])
plt.show()



sns.pairplot(df[['ASTV', 'MSTV', 'ALTV','MLTV', 'Width', 'Tendency', 'NSP']])
plt.show()

# creating correlation between numerical variables and interpreting the correlation of all the variables

sns.heatmap(df[numeric_cols].corr(),
            annot = True,
            center =0,
            square = True,
            cmap = 'coolwarm',
            fmt = '.1f')
plt.show()

# interpreting correaltion between numerical variables
'''ASTV (Short-Term Variability) and ALTV (Long-Term Variability) are inversely related,when short-term fluctuations are high, long-term
 reduced.

Strong positive correlation between Width, Max, and Min which tells that data is consistent
all other variables are having  Weak correlation with Tendency.'''

"""Possible Patterns or Insights
If LB increases gradually, it might indicate rising fetal stress or excitement in late recordings.

If ASTV/ALTV fluctuate rhythmically, it may show natural fetal heart rate variability.

Conclusion:
Key Insights:
The dataset is about tracking fetus heart rate,stable heart rate means healthy fetus
cardiotocography in medical field is a technique that is used to monitor heart rate of the
fetus during pregnancy.Here the first thing to observe is fetal heart rate variability it is
about how the heart rate speed varies from beat to beat.good heart rate variability means
healthy baby.Another risk is abnormal fetal movements in medical term pathological cases
indicate a disease and for these cases fetal movements and abnormal heart rate variability is
high.Also in pathological cases deceleration leads to less oxygen supply to baby.Deceleration
is the term refers to droping of heart beat of baby and coming back to normal.here there are
three cases normal,suspect,pathological.A normal case requires less monitoring and checking
whereas a suspect case should be monitored daily.A pathological case must be given a higher
priority as baby with pathological case is at higher risk and must be monitored daily
"""
